### ISSUE TITLE
help with mapping

### ISSUE THREAD

**Issue by bounceme** [zweifisch/pipe2eval#10]
I am confused about how I would edit this:
```vmap <buffer> <Space> ':![pipe2eval dir]/plugin/pipe2eval.sh text<CR><CR>'```
I only want to remove the second enter but everything I've put into my vimrc has had no effect.Thank you

**Comment by zweifisch** [comment]
I think it's overwritten by this line
https://github.com/zweifisch/pipe2eval/blob/master/plugin/pipe2eval.vim#L11

You can change the default mapping as a workaround
`let g:pipe2eval_map_key = '<Leader>p2e'`

or fork this repo and edit this line directly
https://github.com/zweifisch/pipe2eval/blob/master/plugin/pipe2eval.vim#L8

If you like the idea of this plugin, you should take a look at org-babel 
(warning: it's a emacs package (currently I'm using emacs (with evil) as my primary editor))

**Comment by bounceme** [comment]
```execute "vm <buffer> ". l:map_key ." :!". g:pipe2eval ." ". a:lang . " " . expand('%:p') . "<CR><CR>gv<esc>"```
is the change that worked for me.It might cause a flash if you input a large file because of the reselect but it can be solved with
```set lazyredraw```
