### ISSUE TITLE
Strange js issue

### ISSUE THREAD

**Issue by bounceme** [zweifisch/pipe2eval#11]
try and eval this:
```
(function() {
  return true;
}());
```
and it won't print anything
but this will:
```
(function() { return true; }());
```

**Comment by zweifisch** [comment]
The last line is wrapped with `console.log()` unless it begins with `}` or `)`. https://github.com/zweifisch/pipe2eval/blob/master/plugin/pipe2eval.sh#L183-L190

**Comment by bounceme** [comment]
hey, for line 7 i've tried these two regexes for also ignoring lines starting with 'var'
```
/^[ \t]*\([})]\|var \)/ b
/^[ \t]*[})]\|^[ \t]*var / b
```
neither are working though, do you know what i've done wrong?

**Comment by bounceme** [comment]
does this look correct
```
javascript_eval(){
	cat $TMP_FILE $TMP_FILE.new |\
		sed -e '/^$/d' |\
		sed '$! b
			/^[ \t]*[})]/ b
		$! b
			/^[ \t]*var / b
			s/\(.*\);/console.log(\1);/' > $TMP_FILE.eval
	node --harmony $TMP_FILE.eval 2> $TMP_FILE.error | sed -e 's/^\(.*\)$/\/\/ \1/'
}

```
I'm new to sed

**Comment by zweifisch** [comment]
e4675c82c93f6ac21682bbc63fb6ca2e151a81b0
