### ISSUE TITLE
Gvim support? 

### ISSUE THREAD

**Issue by ReneFroger** [zweifisch/pipe2eval#9]
First, thanks for creating such a awesome plugin!

But will it support Gvim (on Windows 7), by any chance?

**Comment by ReneFroger** [comment]
Why not try Emacs? It's more developer friendly, and doesn't depend on OS like Vim/Gvim, thanks to the famous Emacs Lisp system.

**Comment by zweifisch** [comment]
Yeah, I've already switched. :smile:

**Comment by ReneFroger** [comment]
Good for you! The defaults are horrible and it's pain in the ass to set it up. But once you're onboard, the on-the-fly coding in Elisp is sweet.
